/**
 * Logo manifest — generated by scripts/fetch-logos.mjs, do not edit by hand.
 *
 * Maps deal/venue id to a self-hosted logo in public/logos/. Ids absent here
 * have no logo and fall back to an initials avatar.
 *
 * Logos are the trademarks of their respective owners and are used only to
 * identify the company or venue a listing refers to.
 */

export const logos: Record<string, string> = {
  'abridge': '/logos/abridge.png',
  'airtable': '/logos/airtable.ico',
  'alpha-311': '/logos/alpha-311.ico',
  'anduril': '/logos/anduril.ico',
  'artly': '/logos/artly.png',
  'atombeam': '/logos/atombeam.png',
  'biostate-ai': '/logos/biostate-ai.png',
  'bito': '/logos/bito.png',
  'blushift-aerospace': '/logos/blushift-aerospace.png',
  'chainalysis': '/logos/chainalysis.ico',
  'collider': '/logos/collider.png',
  'crowdcube': '/logos/crowdcube.png',
  'cru-world-wine': '/logos/cru-world-wine.ico',
  'databricks': '/logos/databricks.png',
  'deadly-dozen': '/logos/deadly-dozen.webp',
  'deel': '/logos/deel.png',
  'discord': '/logos/discord.png',
  'endosound': '/logos/endosound.png',
  'epic-games': '/logos/epic-games.ico',
  'equisera': '/logos/equisera.png',
  'equityzen': '/logos/equityzen.png',
  'fanatics': '/logos/fanatics.ico',
  'figure-ai': '/logos/figure-ai.png',
  'flexport': '/logos/flexport.png',
  'forge': '/logos/forge.png',
  'glean': '/logos/glean.png',
  'hevo': '/logos/hevo.png',
  'hiive': '/logos/hiive.png',
  'impossible-foods': '/logos/impossible-foods.png',
  'kraken': '/logos/kraken.ico',
  'lambda': '/logos/lambda.svg',
  'linqto': '/logos/linqto.png',
  'lireka': '/logos/lireka.png',
  'nanoloom': '/logos/nanoloom.webp',
  'nasdaq-pm': '/logos/nasdaq-pm.png',
  'odin': '/logos/odin.png',
  'openai': '/logos/openai.ico',
  'perplexity': '/logos/perplexity.png',
  'ramp': '/logos/ramp.png',
  'rejuvenate-bio': '/logos/rejuvenate-bio.webp',
  'rentberry': '/logos/rentberry.png',
  'republic-eu': '/logos/republic-eu.png',
  'revolut': '/logos/revolut.png',
  'rhealth': '/logos/rhealth.webp',
  'rippling': '/logos/rippling.png',
  'rise-robotics': '/logos/rise-robotics.webp',
  'seedblink': '/logos/seedblink.png',
  'shield-ai': '/logos/shield-ai.png',
  'skild-ai': '/logos/skild-ai.ico',
  'startengine': '/logos/startengine.png',
  'stripe': '/logos/stripe.ico',
  'upmarket': '/logos/upmarket.png',
  'wefunder': '/logos/wefunder.png',
  'whoop': '/logos/whoop.ico',
};

/** Near-white marks that need a dark tile to be visible at all. */
export const darkTile: ReadonlySet<string> = new Set([
  'anduril',
]);

export const logoFor = (id: string): string | undefined => logos[id];
export const needsDarkTile = (id: string): boolean => darkTile.has(id);
